### ISSUE TITLE
social-auth backend for panoptes

### ISSUE THREAD

**Issue by amyrebecca** [zooniverse/theia#47]

**Comment by adammcmaster** [comment]
You might have seen it already, but I've implemented this (and a few of the infrastructure things from your to-do list) in Hamlet already if you want to refer to that https://github.com/zooniverse/hamlet/blob/master/hamlet/zooniverse_auth.py

It might be worth us splitting that into a separate package since it might be useful for a few things.

**Comment by amyrebecca** [comment]
I'll definitely take a look, thank you! It's frustrating that there's no real Django equivalent of Omniauth, I've been struggling with this for a bit.

**Comment by amyrebecca** [comment]
I'm going to include that code in my project to try to get it going and if it works out for me then I'll make a github project for it and publish it as a package

**Comment by amyrebecca** [comment]
@adammcmaster i hate to bother you with questions after you gave me this big head start but how are you getting your panoptes client id and panoptes client secret into the OAuth2 provider? I looked in your project and didn't see it

**Comment by adammcmaster** [comment]
They're set in environment variables and loaded into settings here:

https://github.com/zooniverse/hamlet/blob/master/hamlet/settings.py#L145

**Comment by amyrebecca** [comment]
I almost had it, I was setting _ID instead of _KEY. Thank you! Still working on getting the app to recognize the user, but getting closer.
